# FL Studio hint message icon constants

record = "^b"
happy = "^c"
mouse2 = "^d"
sad = "^e"
triangle_left_orange = "^f"
ffwd = "^g"
warning = "^h"
clock = "^i"
rewind = "^j"
link = "^k"
midi = "^l"
f1 = "^m"
imageline = "^n"
plugin = "^r"
files = "^s"
eye = "^t"
drum_pedal = "^u"
triangle_left = "^v"
triangle_left = "^w"
pencil = "^x"
knife = "^y"
brush = "^z"
